version: '3.1'

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volumes/data:/var/lib/mysql
    env_file:
      - ./docker/mysql/mysql.env
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge